# This configuration file is used to set user specific settings for this project.
# Make adjustement to all settings where needed and save this file as:
# ./config.yaml

## Preparation ------------------

#. 1 Do you want to automatically install packages that are required for this project?
install_packages: "Y"   # choose Y or N

#. 2 Do you want debug messages during the execution of functions?
debug_messages: "Y"     # choose Y on N

# 3. Path to your local Miniconda installation.
# Example: "/home/username/miniconda3"
miniconda_path: "~/ProgramFiles/miniconda3"

# 4. Name of the conda environment where pcraster is installed
# Example: "lisem"
conda_env: "lisem"

# 5. List of subcatchment numbers to analyse.
# see the file /sources/setup/outpoints_description.csv
# for subcatchment names and numbers.
# WARNING: 1 = the whole catchment - very long processing times
# Subcatchments for calibration are: Gulp = 4, Kelmis = 18,
# Watervalderbeek = 10, Eyserbeek = 14.
# You can specify one or more numbers, e.g. [10, 12, 18]
subcatchments: [4, 18]

# 6. resolution to work on, available are 5 , 10 and 20, both is also possible
resolution: [10, 20]
